### PR TITLE
Redirect release branch changelogs to master changelogs

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

**Comment by sunnylovestiramisu** [comment]
/retest

test timed out

**Review by leiyiz — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
