### PR TITLE
[release-1.5] Update go modules

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
Updated the following go modules:
golang.org/x/crypto@v0.17.0
```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
This also looks a little strange. No vendor changes?

**Comment by sunnylovestiramisu** [comment]
No vendor changes, I do not get why it is removing a dependency.

**Comment by msau42** [comment]
If you compare the vendor files to https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/756/files, do they look correct?

**Comment by sunnylovestiramisu** [comment]
The code itself looks the same, is it because the vendor version of crypto in this PR actually has both 1.6 and 1.7?

**Pull request merged**
