### PR TITLE
Update registry k8s.gcr.io -> registry.k8s.io

### PR DESCRIPTION
**Pull request by yashsingh74**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:

This PR updates the registry from k8s.gcr.io to registry.k8s.io

**Which issue(s) this PR fixes**:

Issue: https://github.com/kubernetes/k8s.io/issues/4738

Fixes #

**Special notes for your reviewer**:

- Updated the image registry 

**Does this PR introduce a user-facing change?**:

```release-note
Updated the image registry from k8s.gcr.io to registry.k8s.io, follow https://github.com/kubernetes/k8s.io/issues/4738

```

### CODE REVIEW

**Comment by sunnylovestiramisu** [comment]
Please add release note

**Comment by yashsingh74** [comment]
@sunnylovestiramisu Where to update the release notes?

**Comment by yashsingh74** [comment]
Done @sunnylovestiramisu.
Please review

**Pull request merged**
