### PR TITLE
fix owners formatting

### PR DESCRIPTION
**Pull request by msau42**
For some reason, David is always assigned as the reviewer for all PRs.  Trying to fix that.
/hold

### CODE REVIEW

**Comment by krzyzacy** [comment]
is everyone else joined kubernetes-sigs?

**Comment by krzyzacy** [comment]
or else @davidz627 is just too (un)lucky :-)

cc @cjwagnar

**Comment by msau42** [comment]
Ah I guess everyone else has not joined.  Thanks, will fix it on my end!

**Pull request closed without merging**
