### PR TITLE
Update vendor to get csi-sanity updates

### PR DESCRIPTION
**Pull request by msau42**
csi-sanity issues have been fixed so now the tests can pass and be enabled

### CODE REVIEW

**Comment by davidz627** [comment]
I would recommend locking your dep to a specific version instead of master. See:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/Gopkg.toml#L79

**Comment by msau42** [comment]
I need the latest version to get a fix, so I've locked it to the latest

**Comment by davidz627** [comment]
/lgtm

@msau42 should the fix be cherrypicked to the v0.3.0 release of the csi-test driver then? I see no reason why we should be using an intermediate version for a critical fix. Could you open an issue for the cherry-pick if required?

**Pull request merged**
