### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by saikat-royc**

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm

I think you may also have to enable the release note bot on this repo. Let me try to dig up which repo the config was in

**Comment by saikat-royc** [comment]
> the release note bot on this repo. Let me try to dig up which repo the config was in

ok let me know. thanks

**Comment by msau42** [comment]
https://github.com/kubernetes/test-infra/blob/7203fc4ecc9ecd2740560c4ed6bae515e51722d9/config/prow/plugins.yaml#L854

**Pull request merged**
