### PR TITLE
images: use k8s-staging-test-infra/gcb-docker-gcloud

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523

### CODE REVIEW

**Comment by mattcary** [comment]
@spiffxp excuse my ignorance, do the presumbit jobs check that the cloud build is working? Or, in the unlikely case you've made a mistake here, should we just watch the cloud build for failures on the next release we push out?

@saikat-royc

**Comment by spiffxp** [comment]
There should be a postsubmit that runs as soon as this merges.  You can click through to the merge commit and see postsubmit statuses reported there.  I've been keeping an eye on these as they've merged

**Comment by spiffxp** [comment]
To more directly answer your question, no, there aren't presubmits that validate cloudbuild config changes

**Comment by mattcary** [comment]
/lgtm

Makes sense, thanks for tracking.

**Comment by leiyiz** [comment]
@spiffxp I recently made changes to this file while I didn't see your PR. can you rebase this PR?

/approve

**Pull request merged**
