### PR TITLE
Support NodeStageVolume for the driver

### LINKED ISSUE #47: Handle NodePublish in compliance with CSI spec
Reference: https://github.com/kubernetes/kubernetes/issues/75535

During NodePublish, kubernetes today creates the target path (for e.g. /var/lib/kubelet/pods/<POD ID>/volumes/kubernetes.io~csi/<VolumeID>/mount).
This behavior will go away in future kubernetes version, where k8s would only create the parent dir  /var/lib/kubelet/pods/<POD ID>/volumes/kubernetes.iocsi/<VolumeID>

It is the driver's responsibility to ensure the target path is created (and delete during node unpublish).
Update the current node publish code, to check for existence of the target path and create one if needed (for linux), before proceeding to mount call.

### PR DESCRIPTION
**Pull request by saikat-royc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #47

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Support NodeStageVolume for Filestore CSI driver, and NodePublish should create the target path if missing.
```

### CODE REVIEW

**Comment by msau42** [comment]
There is a known issue coordinating NodeUnstage and PV deletion. We may want to wait for that to be fixed before supporting this: https://github.com/kubernetes/kubernetes/issues/94108

**Comment by jingxu97** [comment]
Could you put some description on why NodeStageVolume is needed for filestore driver?

**Comment by saikat-royc** [comment]
w.r.t kubernetes/kubernetes#94108, 
I tried out the pod delete experiment on 1.18.8, pod and pvc delete seems be working as expected for filestore csi driver.
```
saikatroyc@saikatroyc:~/go/src/sigs.k8s.io/gcp-filestore-csi-driver$ kc version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
On deleting the pod, node unpublish and unstage gets called.
```
I0905 18:32:01.588182       1 utils.go:52] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0905 18:32:01.588307       1 utils.go:53] GRPC request: {"target_path":"/var/lib/kubelet/pods/0a545840-01a3-4574-b047-6d6af861efde/volumes/kubernetes.io~csi/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/mount","volume_id":"modeInstance/us-central1-b/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/vol1"}
I0905 18:32:04.635475       1 node.go:356] Unmounting "/var/lib/kubelet/pods/0a545840-01a3-4574-b047-6d6af861efde/volumes/kubernetes.io~csi/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/mount"
I0905 18:32:04.697977       1 utils.go:58] GRPC response: 
I0905 18:32:04.708942       1 utils.go:52] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0905 18:32:04.708983       1 utils.go:53] GRPC request: {}
I0905 18:32:04.708990       1 utils.go:58] GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > 
I0905 18:32:04.710584       1 utils.go:52] GRPC call: /csi.v1.Node/NodeUnstageVolume
I0905 18:32:04.710685       1 utils.go:53] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/globalmount","volume_id":"modeInstance/us-central1-b/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/vol1"}
I0905 18:32:04.710724       1 node.go:356] Unmounting "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/globalmount"
I0905 18:32:07.816799       1 node.go:253] NodeUnstageVolume succeeded on modeInstance/us-central1-b/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/vol1 from /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/globalmount
I0905 18:32:07.816831       1 utils.go:58] GRPC response: 
```

pvc still remains as expected:
```
saikatroyc@saikatroyc:~/go/src/sigs.k8s.io/gcp-filestore-csi-driver$ kc get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
test-pvc   Bound    pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5   1Ti        RWX            csi-filestore   56m
```

then on delete of pvc, the volume delete is called as expected.
```
I0905 18:37:02.867708       1 utils.go:52] GRPC call: /csi.v1.Controller/DeleteVolume
I0905 18:37:02.868013       1 controller.go:190] DeleteVolume called with request {modeInstance/us-central1-b/pvc-08ce7de2-e9c4-48e8-9de6-a1e9c6e3d9c5/vol1 map[] {} [] 0}
I0905 18:37:02.951722       1 file.go:219] Starting DeleteInstance cloud operation
```

@msau42  the issue (unstage called after delete) reported in kubernetes/kubernetes#94108 needs additional debugging as to what exactly is the setup there. Will followup on it.

**Comment by jingxu97** [comment]
@saikat-royc did you try to call delete PVC before deleting pod to see whether PVC is deleted before unstage is finished?

also just wondering why NodeStageVolume is required for the driver now? Thanks!

**Comment by saikat-royc** [comment]
@mattcary / @msau42  given that the issue in kubernetes/kubernetes#94108 is already root caused and is an issue across all csi drivers, can we proceed with this patch review.

For  the race fix https://github.com/kubernetes/kubernetes/pull/94737, I am working on reviewing the test failures and fixing them (for. e.g. some of the tests failed due to insufficient wait timeout).

**Comment by mattcary** [comment]
> @saikat-royc did you try to call delete PVC before deleting pod to see whether PVC is deleted before unstage is finished?
> 
> also just wondering why NodeStageVolume is required for the driver now? Thanks!

@jingxu97 based on guidance from the filestore team we are mounting the filestore instance at nodestage and then bind-mounting for each pod in node publish. Filestore has connection limits and while it's possible that the kernel does the right thing with multiple mounts to the same instances, having an explicit node stage appears to be the right way to do this.

@saikat-royc Please clarify anything I got wrong :-)

**Comment by msau42** [comment]
Can you double check if the bind mount actually saves on connections? I vaguely recall when I was making subpath fixes, I think each subpath mount was its own connection

**Comment by mattcary** [comment]
> Can you double check if the bind mount actually saves on connections? I vaguely recall when I was making subpath fixes, I think each subpath mount was its own connection

Here is an extract of details from a couple of email threads.

(Saikat did) a small experiment where I listed the tcp connections on the nfs server (at server "netstat -an |  grep <nfs_server_ip>:2049"), a single tcp connection was established, for multiple mounts of the same share at the client.

From a filestore expert at google:
If you mount the exact same NFS share multiple times:
 - Separate NFS mounts will still share the direntry (and other?) cache between them (this is required for coherency).
 - I'm pretty sure the NFS client will still use a single connection to the server (the connection will be shared)
So it probably doesn't add much to mount multiple times, performance-wise. You may want to do it for other reasons (having a mount/unmount per container and not having to worry about the server-wide state? not sure it matters for you).

AFAIK for Filestore high-scale there's a 600-connection-per-server-node limit, which means 3600 connections per filestore instance. I'm not sure about Filestore Basic - if you're interested I can direct you to someone from that team. I'm also not very familiar with bind mounts but - I don't think bind mounts show up at all on the NFS server (they are terminated on the client side, and the server only sees the regular NFS mount that was created by the client).

Given that the nfs connection is shared, a bind mount of a share mounted at nfs client should also share the underlying connection. I would be very surprised if adding them changed anything regarding the NFS connection itself.

**Comment by msau42** [comment]
Cool, thanks for verifying. I think in my case, the subpath mount is considered a new share and that's why a new connection was created.

ie, the main share is at server:/share, and the subpath bind mount is at server:/share/subdir

**Comment by mattcary** [comment]
/lgtm

Thx for missing directory from nodestage commit

**Pull request merged**
