### PR TITLE
Update changelog for release v1.6.2, v1.5.8, v1.3.18

### PR DESCRIPTION
**Pull request by pwschuurman**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

Update release specific changelog for recent gcp-filestore-csi-driver releases

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by leiyiz — COMMENTED** [review]
/lgtm
/approve

**Comment by tyuchn** [comment]
removing the hold label since https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/579 has been merged

**Pull request merged**
