### PR TITLE
Automated cherry pick of #381: Fix of driver error wrapping hides error codes and
#397: Fix error categorization and handling
#398: Simplify status.Error to status.Errorf in controller.go to
#402: Fix firestore error logging and wrapping

### PR DESCRIPTION
**Pull request by hsadoyan**
Cherry pick of #381 #397 #398 #402 on release-1.3.

#381: Fix of driver error wrapping hides error codes and
#397: Fix error categorization and handling
#398: Simplify status.Error to status.Errorf in controller.go to
#402: Fix firestore error logging and wrapping

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by leiyiz** [comment]
edited release note to `NONE`
/ok-to-test

**Comment by leiyiz** [comment]
I think there might be some problems here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-filestore-csi-driver/406/pull-gcp-filestore-csi-driver-verify/1613230876240384000/#1:build-log.txt%3A123-133

**Comment by hsadoyan** [comment]
> I think there might be some problems here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-filestore-csi-driver/406/pull-gcp-filestore-csi-driver-verify/1613230876240384000/#1:build-log.txt%3A123-133

Yeah a dependency was removed that 1.3 still needs but master does not. I added it back.

**Review by leiyiz — COMMENTED** [review]
/lgtm

**Pull request merged**
