### PR TITLE
[WIP] update dependencies

### PR DESCRIPTION
**Pull request by leiyiz**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leiyiz** [comment]
@olemarkus could these failures be related to this PR? https://github.com/kubernetes-sigs/boskos/pull/141

**Comment by olemarkus** [comment]
Which one did you have in mind? I saw some build failures due to this change: https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/338/files#diff-6ea56a6be0f530a722fa9a5e04c47bbacd09301411b5ab5f08ccd220bf49f83cR179

**Comment by leiyiz** [comment]
> Which one did you have in mind? I saw some build failures due to this change: https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/338/files#diff-6ea56a6be0f530a722fa9a5e04c47bbacd09301411b5ab5f08ccd220bf49f83cR179

not the integration one, I meant the `pull-gcp-filestore-csi-driver-sanity`, `pull-gcp-filestore-csi-driver-verify` and `pull-gcp-filestore-csi-driver-e2e` failures

**Comment by olemarkus** [comment]
Yeah. It could be an implicit side effect of a significant number of dependency updates in k8s.io/test-infra that then was ported into boskos. And then these jobs use an image that also pulls test-infra?

Could it also have an older go version?

**Comment by leiyiz** [comment]
> Yeah. It could be an implicit side effect of a significant number of dependency updates in k8s.io/test-infra that then was ported into boskos. And then these jobs use an image that also pulls test-infra?
> 
> Could it also have an older go version?

I think `k8s.io/test-infra` dependency actually comes from boskos: `-- sigs.k8s.io/boskos/client`? we don't use test-infra directly. Can you clarify what image are you talking about?

**Comment by leiyiz** [comment]
closing this pr and replace by https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/340 with limited blast radius

**Pull request closed without merging**
