### PR TITLE
Fix typos in README

### LINKED ISSUE #914: Fix typos in README.md
There are some typos in README like
`./deploy/kubernetes/cluster-setup.sh`
and 
`Make and build the image if desploying new master branch.`

### PR DESCRIPTION
**Pull request by riteshghorse**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fixes the typos in README.

**Which issue(s) this PR fixes**:
#914

Fixes #914 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by riteshghorse** [comment]
CC: @eipi-one

**Review by leiyiz — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
