### PR TITLE
[release-1.4] Cherry-pick 521, 527 and 532 to release 1.4 #573

### PR DESCRIPTION
**Pull request by judemars**
This is an automated cherry-pick onto release-1.3 of:

- #521 
- #527 
- (fixes a small bug with 521) #532

```release-note
Handle CreateBackupURI errors as InvalidArgument
```

### CODE REVIEW

**Review by leiyiz — COMMENTED** [review]
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/527/files#diff-6ea56a6be0f530a722fa9a5e04c47bbacd09301411b5ab5f08ccd220bf49f83cR725

this change is missing from here.. is there any reason for it?

**Comment by judemars** [comment]
> https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/527/files#diff-6ea56a6be0f530a722fa9a5e04c47bbacd09301411b5ab5f08ccd220bf49f83cR725
> 
> this change is missing from here.. is there any reason for it?

@leiyiz there were merge conflicts so I decided to drop it since it was not a functional change and would likely cause more merge conflict with later potential backports (like whichever change fixed the method name Backp -> Backup). I just re-added it though.

**Comment by judemars** [comment]
Woops sorry didn't mean to close, just meant to resolve the comment

**Comment by judemars** [comment]
Ran verify + uts locally:

```

 % git branch    
* automated-cherry-pick-of-#521-upstream-release-1.3
...

 % hack/verify_all.sh
Verifying gofmt
Verifying govet

 % test/run_unit.sh      
+ readonly PKGDIR=sigs.k8s.io/gcp-filestore-csi-driver
+ PKGDIR=sigs.k8s.io/gcp-filestore-csi-driver
+ go version
go version go1.19.4 linux/amd64
+ go test -mod=vendor -timeout 30s sigs.k8s.io/gcp-filestore-csi-driver/cmd/...
?   	sigs.k8s.io/gcp-filestore-csi-driver/cmd	[no test files]
?   	sigs.k8s.io/gcp-filestore-csi-driver/cmd/webhook	[no test files]
+ go test -mod=vendor -timeout 30s sigs.k8s.io/gcp-filestore-csi-driver/pkg/...
?   	sigs.k8s.io/gcp-filestore-csi-driver/pkg/cloud_provider	[no test files]
ok  	sigs.k8s.io/gcp-filestore-csi-driver/pkg/cloud_provider/file	0.053s
?   	sigs.k8s.io/gcp-filestore-csi-driver/pkg/cloud_provider/metadata	[no test files]
ok  	sigs.k8s.io/gcp-filestore-csi-driver/pkg/csi_driver	0.152s
ok  	sigs.k8s.io/gcp-filestore-csi-driver/pkg/metrics	0.042s
ok  	sigs.k8s.io/gcp-filestore-csi-driver/pkg/util	0.098s
ok  	sigs.k8s.io/gcp-filestore-csi-driver/pkg/webhook	0.079s
```

**Pull request closed without merging**
